blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions & Discussions
    url: https://github.com/knightsri/resume-forge/discussions
    about: Ask questions, share ideas, or discuss Resume Forge with the community
  - name: 📚 Documentation & Getting Started
    url: https://github.com/knightsri/resume-forge/blob/main/docs/getting-started.md
    about: Check the getting started guide and documentation first
  - name: 🔧 Troubleshooting Guide
    url: https://github.com/knightsri/resume-forge/blob/main/docs/troubleshooting.md
    about: Common issues and solutions